In [1]:
import numpy as np

In [30]:
class Perceptron:
    def __init__ (self, eta, n_iter, rnd=1):
        self.eta = eta
        self.n_iter = n_iter
        self.rnd = rnd
    
    def net_input(self, X):
        return np.dot( X, self.w )
    
    def fit(self, X, y):
        rgen = np.random.RandomState(self.rnd)
        
        self.w = rgen.normal(loc=0.0, scale=0.01, size=X.shape[1])
        for _ in range(self.n_iter):
            for xi, target in zip(X,y):
                uprgade = self.eta * ( target - self.predict(X) )
                self.w += uprgade * xi 
                
    def predict(self, X):
        return np.where( self.net_input(X) >= 0, 1, -1 )

In [31]:
pers1 = Perceptron(0.1, 50, 1)

In [32]:
pers1.fit(np.array( [[1,2,3], [2,4,6], [3,5,7]] ),np.array( (1,2,3)) )

In [15]:
pers1.w

array([ 0.01624345, -0.00611756, -0.00528172])

In [12]:
pers2 = Perceptron(0.1, 50, 17)

In [14]:
pers2.fit(np.array( [[1,2,3], [2,4,6], [3,5,7]] ),  1 )
pers2.w

array([ 0.00276266, -0.01854628,  0.00623901])

In [41]:
x3 = [1 , 6, 7, 4, 2, 8, 43, 6, 0 ]
y3 = [-1, 8 ,4, 3,5 ,9 , 0 , -10, 18 ]

x4 = [20 , 60, 25, 48, 27, 43, 43, 45, 10 ]
y4 = [45, 65 ,34, 83,35 ,59 , 40 , 10, 18 ]

X1 = np.array((x3, y3) )
X2 = np.array((x4, y4) )

y = np.ones( (18) )
y[9:] *= (-1)


X = np.zeros( (18, 2) )
X[:9] = X1.T
X[9:] = X2.T


array([[  1.,  -1.],
       [  6.,   8.],
       [  7.,   4.],
       [  4.,   3.],
       [  2.,   5.],
       [  8.,   9.],
       [ 43.,   0.],
       [  6., -10.],
       [  0.,  18.],
       [ 20.,  45.],
       [ 60.,  65.],
       [ 25.,  34.],
       [ 48.,  83.],
       [ 27.,  35.],
       [ 43.,  59.],
       [ 43.,  40.],
       [ 45.,  10.],
       [ 10.,  18.]])

In [42]:
pers = Perceptron(0.1 ,50,1)

In [45]:
pers.net_input(X.T)

ValueError: shapes (2,18) and (2,) not aligned: 18 (dim 1) != 2 (dim 0)